# Build Windows workflow
name: build-windows

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master,beta]
    paths-ignore:
      - "docs/**"
      - "dist/**"
      - "images/**"
      - "**.md"
      - "**.gitignore"
      - "**clog.py"
      - "**LICENSE"
      - "**-mac**"
      - "**-linux**"

    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows
        run: pyinstaller --clean --noconfirm specs/windows-terminservice.spec --add-data "tools/cloudscraper;./cloudscraper/"
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'dist/windows-terminservice --force'

          # The name of the user that will be displayed as the author of the commit
          # Default: depends on the default_author input
          author_name: build_windows-workflow

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
          # cwd: '.'

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "Windows build workflow"

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          # push: false

          # Remove
          remove: ''

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          # tag: ''
